### ISSUE TITLE
allow broader keyword search to find genes

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#11]
type something from the gene name, or a pathway it's in, and find the gene of interest.

E.g. typing "Epidermal" should find "EGFR" (Epidermal Growth Factor Receptor).

Need to provide @Zaknarfen with things to index.

**Comment by annagree** [comment]
@Zaknarfen @diegof18 Let's discuss how hard this would be to implement.

**Comment by annagree** [comment]
partially solved by adding Ensembl gene ID to search
