### ISSUE TITLE
INPP5D coexpression network is too dense

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#141]
If you spin up a local version of the app and go to http://localhost/genes/(genes-router:gene-details/ENSG00000168918) it looks very busy

Is it possible to adaptively filter based on the number of genes that are being displayed?  E.g. if the number of genes at a given filter level is greater than say 50, you increase the level of filtering (and give users the ability to control that filtering)?

**Comment by kdaily** [comment]
yes close
