### ISSUE TITLE
Copy in mobile is justified, this should be left aligned 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#184]
ie: the description on the gene page

**Comment by Zaknarfen** [comment]
The black paragraphs with left alignment are using this at the moment:

```
    text-align: justify;
    text-align-last: left;
```

If we change, we would go from this:

![image](https://user-images.githubusercontent.com/4223973/43735888-3d451a8e-9992-11e8-8a85-3ae2f0862f60.png)

to this, on mobile:

![image](https://user-images.githubusercontent.com/4223973/43735931-552b0bcc-9992-11e8-9436-f5bb1c1c050a.png)

Should i change it? @stockards @annagree?

**Comment by stockards** [comment]
Please use the 2nd option.

**Comment by Zaknarfen** [comment]
Fixed in the latest patch.
