### ISSUE TITLE
boxplot- axis not updating with new filter

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#193]
The y axis does not update when a new filter is selected. 
<img width="1301" alt="screen shot 2018-07-09 at 1 36 10 pm" src="https://user-images.githubusercontent.com/40642407/42474665-2cb23312-837d-11e8-9394-fc89b4ab59e3.png">

**Comment by kdaily** [comment]
if it's performance it's not just affecting this component, so closing.
