### ISSUE TITLE
 Fix spacing on Network Gene section 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#194]

**Comment by Zaknarfen** [comment]
Is this still an issue? This is what I see currently:

![image](https://user-images.githubusercontent.com/4223973/43732161-33ebddf2-9987-11e8-8609-4b57a41365e8.png)

**Comment by stockards** [comment]
If we could provide slightly more space between the different connections like the mock ups have that would be awesome. Let me know if you have any questions about this. 
<img width="577" alt="screen shot 2018-08-06 at 1 54 52 pm" src="https://user-images.githubusercontent.com/38479289/43740562-692371da-9980-11e8-9710-817032763f72.png">

**Comment by Zaknarfen** [comment]
I believe I fixed this. Closing it.
