### ISSUE TITLE
Duplication of genes in nominated target list

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#209]
Genes are duplicated in list of nominated targets. 
<img width="1270" alt="screen shot 2018-07-09 at 2 41 44 pm" src="https://user-images.githubusercontent.com/40642407/42477548-5cb147de-8386-11e8-981d-5d875c014ef2.png">

**Comment by kdaily** [comment]
db related bug, @Zaknarfen addressed this.
