### ISSUE TITLE
help pages

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#21]
for how to use the site

what are all of the plots

what does it all mean

**Comment by annagree** [comment]
add link to tutorial video(s) from the help page.

**Comment by annagree** [comment]
Stockard has mocked up a Help page. We need this page created and should be linked to from "Help" in the footer of the site.

**Comment by Zaknarfen** [comment]
@annagree can you add the link here to the video here or even the embed video so I can put there? The help page was committed to `develop` already.

**Comment by annagree** [comment]
Great! The link to the video is here: https://www.youtube.com/watch?v=ruDwBippTMU
Sorry I don't know how to do the embedding!

**Comment by Zaknarfen** [comment]
The video is already in the Agora website, it is not responsive yet.

**Comment by annagree** [comment]
Try to change iframe to improve video sizing. Adjust the spacing of the Other Questions section to match Figma design.

**Comment by Zaknarfen** [comment]
We can close this now. Fixed the issues.
