### ISSUE TITLE
Test coverage across multiple browsers and os

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#217]
OS
- [ ] Mac
- [ ] Linux
- [ ] Windows

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge (internet explorer)

Mobile
- [ ] iPhone
- [ ] Android

**Comment by Zaknarfen** [comment]
I think we can close this, I added the `stylelint` to the project. It uses the [caniuse](https://caniuse.com/) website through a plugin and checks all the style rules and incompatibilities. We are very close to finishing the portability list in #328. This is regarding styles.

For functionality portability, we already use a `polyfills` file. It adds missing functions for old browsers, so if we run into anything it would be easy to fix.
