### ISSUE TITLE
for genes with no data available in the gene_info.json 

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#260]
have a coming soon dialog in the drop down, but don't let the user do anything

**Comment by Zaknarfen** [comment]
This would be kinda tricky to do. Can we show a message on the screen? like those closeable messages. Maybe right above the dropdowns? ```A, B, and C: Coming Soon``` with a warning color.

Would this be for models only or do we need this for tissues as well?

**Comment by annagree** [comment]
might be duplicate of #344
