### ISSUE TITLE
add content about mousing over dot for more info on RNA-seq boxplot

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#284]

**Comment by Zaknarfen** [comment]
Can you give me an example of this @annagree?

**Comment by annagree** [comment]
We still need to write the content- I will assign to me for now. Thanks!

**Comment by annagree** [comment]
**Current content:**
After selecting a tissue and statistical model, you will be able to see whether the selected gene is differentially expressed between AD cases and controls The box plot depicts how the differential expression of the selected gene of interest (red dot) compares with expression of other genes in the tissue.

**Updated content:** (only the last sentence _italicized_ needs to be updated)
After selecting a tissue and statistical model, you will be able to see whether the selected gene is differentially expressed between AD cases and controls The box plot depicts how the differential expression of the selected gene of interest (red dot) compares with expression of other genes in the tissue. _Summary statistics can be viewed by hovering over the red dot._

**Comment by Zaknarfen** [comment]
Closing this as fixed.
