### ISSUE TITLE
create terms and privacy page

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#292]
Create page to host Terms and Conditions of Use and Privacy Policy. Also add link to this page from the footer.

This google doc contains the content for the page (contains content for both Privacy and Terms):
https://docs.google.com/document/d/1cteASPkJzl3CRtTJxgPtuwRzZ26Ve-k_MbVMkYMAsTY/edit?usp=sharing

**Comment by kdaily** [comment]
I will add the PDF to the assets folder.

**Comment by kdaily** [comment]
use route `/terms` for the page.

**Comment by Zaknarfen** [comment]
The page was created, I just the need `.pdf`. It wasn.t inside the `assets` last time I checked.

**Comment by kdaily** [comment]
See #311

**Comment by kdaily** [comment]
"Download the Terms of Use and Privacy Policy [here](http://file.pdf)."

**Comment by Zaknarfen** [comment]
Changed text and added file call.
