### ISSUE TITLE
site is unavailble due to certificate issue

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#308]
highest priority to fix

**Comment by blogsdon** [comment]
<img width="1435" alt="screen shot 2018-07-18 at 11 04 15 am" src="https://user-images.githubusercontent.com/1447157/42899483-046971b8-8a7b-11e8-996e-87f94766836f.png">

**Comment by kdaily** [comment]
Duplicate of #98. We will roll back to http.

**Comment by kdaily** [comment]
fixed.
