### ISSUE TITLE
update content for "Overall Expression of Selected Gene Across Tissues"

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#309]
Change content under "Overall Expression of Selected Gene Across Tissues" as follows:

Current: Meaningful expression is considered to be anything greater than five CPM.

Change to:  Meaningful expression is considered to be anything greater than five CPM, as indicated by the horizontal red line in the graph.

**Comment by annagree** [comment]
@kdaily we discussed but I don't remember if you fixed this already

**Comment by Zaknarfen** [comment]
Current phrase says:

> This plot depicts the median expression of the selected gene across tissues (brain regions) in the dataset, as measured by RNA-seq read counts per million (CPM) reads. Meaningful expression is considered to be anything greater than five CPM (referenced by red line in the plot).

Can we close this? @annagree @kdaily

**Comment by annagree** [comment]
Yes- I think Kenny had fixed already. Closing.
