### ISSUE TITLE
update genetic association data on site

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#313]
with current version of syn12514826

**Comment by blogsdon** [comment]
@kdaily if we can fix this sooner let me know - definitely irked some collaborators by not having APOE as an AD genetic risk gene haha

**Comment by blogsdon** [comment]
we're definitely getting a lot of feedback on this -should try to fix ASAP

**Comment by blogsdon** [comment]
this should be one of the top priorities for the patch release

**Comment by kdaily** [comment]
This is addressed with version 6 of the data. @Zaknarfen can you test?

**Comment by Zaknarfen** [comment]
I can see `APOE` as a gene, what else do we need to test?
