### ISSUE TITLE
missing nominated targets in gene info data

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#314]
currently we're missing the following genes that are nominated targets

IL10
CXCL10
NEFL
NR1H4
CYP3A43
SULT2A1
HSPB2

**Comment by Zaknarfen** [comment]
There is an `IL10RA`, [here](http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000110324). The rest seems to be missing.

**Comment by kdaily** [comment]
Was problem with the data. Will update data ASAP.

**Comment by kdaily** [comment]
ensembl gene ids are wrong for these, they don't exist at ensembl.


|team                | rank|ensembl_gene_id |
|:-------------------|----:|:---------------|
|Mayo-UFL-ISB        |    2|ENSG00000136634 |
|Mayo-UFL-ISB        |    5|ENSG00000169245 |
|MSSM                |   19|ENSG00000104725 |
|Duke                |    3|ENSG00000012504 |
|Duke                |   13|ENSG00000021461 |
|Duke                |   18|ENSG00000105398 |
|Broad-Rush-Columbia |    6|ENSG00000170276 |

**Comment by kdaily** [comment]
not in original rnaseq diff expr data.

**Comment by blogsdon** [comment]
let's discuss on the call on 7/26/18

**Comment by kdaily** [comment]
These are now all in the `geneInfo.json` file from data version 6.
