### ISSUE TITLE
not all brain regions are showing for some genes

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#316]
for example for CD33 http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000105383)

**Comment by blogsdon** [comment]
looks like gene is not present in ROSMAP and MSBB data-sets, maybe due to low count issues, we should figure out how to represent this edge case in the november release

**Comment by kdaily** [comment]
I'm going to unassign myself from this, @annagree - this is a data representation issue, not a data processing issue *until* we are considering reprocessing this data. The answer to this question will likely require @th1vairam.

**Comment by annagree** [comment]
This is due to the fact that some genes aren't found in some tissues. 
Need to understand how we generally deal with missingness in RNAseq pipeline.

**Comment by annagree** [comment]
@annagree to add some language to explain why genes might not be found in some brain regions.

**Comment by annagree** [comment]
Want a way to define schema for data. 
This is a conversation with the Engineering team about data management going forward.

**Comment by annagree** [comment]
Need an example of this happening.
One fix is to include NA when expression data is missing in gene_info.json. Then could be rendered on the plot.
