### ISSUE TITLE
loading page shakes in fullscreen mode in chrome

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/Agora#319]
See slack channel for example video, can't attach on GitHub due to size constraint (I think). 

Clicking on a gene in fullscreen mode in Chrome (67.0.3396.99) brings me to a jittering loading screen. Doesn't seem to happen in windowed mode.

**Comment by Zaknarfen** [comment]
Weird, I tested here in chrome ```Version 67.0.3396.99 (Official Build) (64-bit)``` and I used the same steps you did, no flicker. Let me investigate a bit more.

**Comment by Zaknarfen** [comment]
Did the last commit fix this @allaway?

**Comment by allaway** [comment]
@Zaknarfen Is this the current live version?

**Comment by Zaknarfen** [comment]
Yes, it is. I'll try some other fixes.

**Comment by Zaknarfen** [comment]
I made another patch, let me know how it goes @allaway.

**Comment by allaway** [comment]
Hmm. It still appears to be an issue. Were you able to reproduce this anywhere? Unfortunately I only have one laptop with this particular display, so I can't test it anywhere else.

**Comment by allaway** [comment]
@Zaknarfen I still see the flickering. Looking a bit closer, it looks like the Chrome scrollbar is appearing and disappearing, causing a flickering appearance.

**Comment by Zaknarfen** [comment]
I was having a similar thing in mobile. But in my case there was an extra space, I thought that could be the flicker you see. I'll try another thing tomorrow.

**Comment by allaway** [comment]
It was on, but toggling that didn't appear to make a difference.

**Comment by annagree** [comment]
Closing because we can't replicate this.
