### ISSUE TITLE
fix text formatting in network widget

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#323]
Text formatting for "true" or "false" field is currently not consistent across all categories, in terms of capitalization (and I think also the color or bolding is slightly different??). 

Please update formatting for the true/false field for the top two categories (**AD Genetic Association** and **Nominated Target**) so that the color is the same as for **Brain eQTL** and the first letter is capitalized. 

See blue arrows in the attached screenshot for more context.
<img width="985" alt="screen shot 2018-07-25 at 11 32 08 am" src="https://user-images.githubusercontent.com/40642407/43220522-1d054088-8fff-11e8-9279-77873676e617.png">

**Comment by Zaknarfen** [comment]
Yea, I agree most things about the styling were my doing and the ones in the network got a bit different because Diego did it. I'll fix this to keep consistency.

**Comment by Zaknarfen** [comment]
Closing this as fixed.
