### ISSUE TITLE
change banner title on About page

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#325]
Currently the Banner says "About Agora", please change to just "About" 
(it is redundant with the first header below so it looks kind of funny)

<img width="720" alt="screen shot 2018-07-26 at 3 27 38 pm" src="https://user-images.githubusercontent.com/40642407/43292018-8fcbdf16-90e8-11e8-9482-f9a71d69aa2c.png">

**Comment by Zaknarfen** [comment]
Closing this as fixed.
