### ISSUE TITLE
indicate which browsers are supported for Agora

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#327]
@jay-hodgson can you weigh in on what browsers we should officially support (including versions)?

**Comment by Zaknarfen** [comment]
According to [this](https://www.sitepoint.com/browsers-website-support/) article here is the breakdown of browsers:

> The top ten desktop browsers according to StatCounter for May 2017 were:
> 
> Chrome — 59.37% market share
> Firefox — 12.76%
> Safari — 10.55%
> IE — 8.32%
> Edge — 3.42%
> Opera — 1.99%
> Android (tablet) — 1.24%
> Yandex Browser — 0.48%
> UC Browser — 0.41%
> Coc Coc — 0.33%
> 
> Mobile now accounts for 54.25% of all web use so we also need to examine the top ten phone browsers:
> 
> Chrome — 49.23%
> Safari — 17.73%
> UC Browser — 15.89%
> Samsung Internet — 6.58%
> Opera — 5.03%
> Android — 3.75%
> IEMobile — 0.68%
> BlackBerry — 0.26%
> Edge — 0.15%
> Nokia — 0.12%

The article stresses that we should build this list based on our audience. Excluding that fact, we can come up with a list by percentage, e.g. greater than `1%` usage.

With a rule of `> 1%`, that we are actually currently using in style linting, we get to the following:

**Desktop**

Chrome — 59.37% market share
Firefox — 12.76%
Safari — 10.55%
IE — 8.32%
Edge — 3.42%
Opera — 1.99%
Android (tablet) — 1.24%

**Mobile**

Chrome — 49.23%
Safari — 17.73%
UC Browser — 15.89%
Samsung Internet — 6.58%
Opera — 5.03%
Android — 3.75%

We could reduce the list based on demographics, but this makes a great first draft. As a side note, our current application has the most style problems with `Opera Mini` and `IE` in particular.

**Comment by gatof81** [comment]
is there any specific requirement to support from any IE version? the use of this specific browser is mostly tight to corporations that have their system freeze and can't install another option like banks, etc.

**Comment by annagree** [comment]
Documentation on help page- which browsers are not supported.

**Comment by annagree** [comment]
Need a final list of supported and unsupported browsers, then can develop content.
Also need to determine where/how to show this?
