### ISSUE TITLE
design for what to show when a gene doesn't have a boxplot or network diagram

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#331]
For some of the nominated genes, there is no expression data- need a design for what will be returned for the plots in those cases.

**Comment by annagree** [comment]
@stockards please prioritize for Sprint 1.
When you have designs, please comment here and assign to Diego and Renan.

**Comment by annagree** [comment]
As discussed in the Stand Up, when data for a gene is not available the entire widget should say "not available" or something similar. Will need designs for any of the widgets with graphs, so that includes Overall Expression (bar chart), Differential Expression (box plot), Consistency (forest plot), and Similarly Expressed genes (Network widget; for this one, the "not available" should include the side panels)

**Comment by stockards** [comment]
Designs can be found within the Figma file above the current screen for Network Expanded.

**Comment by annagree** [comment]
@stockards Use this text: "No expression data is currently available".

**Comment by stockards** [comment]
<img width="718" alt="screen shot 2018-08-23 at 5 31 27 pm" src="https://user-images.githubusercontent.com/38479289/44558702-7f258400-a6fa-11e8-947a-b8a35c183959.png">
<img width="700" alt="screen shot 2018-08-23 at 5 32 07 pm" src="https://user-images.githubusercontent.com/38479289/44558703-7f258400-a6fa-11e8-88df-7134f761a6c6.png">
