### ISSUE TITLE
plan for managing data export from Agora

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#335]

**Comment by annagree** [comment]
Renan to share the current underlying data so we can decide which columns and labels to use.

**Comment by Zaknarfen** [comment]
The data structure is like this in json:

```adj_p_val: 0.1201
ci_l: -0.736
ci_r: 0.0076
ensembl_gene_id: "ENSG00000128564"
fc: 0.777
hgnc_symbol: "VGF"
logfc: -0.364
model: "AD Diagnosis (males and females)"
study: "MayoRNAseq"
tissue: "CBE"  
_id: "5b9199ec7b73e58cbacbf544"
```

And in CSV:

[result.zip](https://github.com/Sage-Bionetworks/Agora/files/2358936/result.zip)

**Comment by annagree** [comment]
This is currently blocked- we need to decide how much of a priority this is before moving forward. There are broader questions to consider around overall user experience and expectations across the other Sage products (eg. why isn't it as easy to download from Synapse or AMP-AD Portal).
