### ISSUE TITLE
new design of arrows in network widget 

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#336]
should be undirected

**Comment by stockards** [comment]
What are the details on this ticket?

**Comment by annagree** [comment]
@blogsdon can confirm, but I believe this issue was related to the fact that the arrows imply that the gene on the left leads to the gene on the right. But, there isn't a directional relationship between the genes. Are there other ways to indicate that they are paired but not imply a direction?

**Comment by annagree** [comment]
For example, the arrows here do imply directionality: 
<img width="1027" alt="screen shot 2018-10-02 at 3 54 55 pm" src="https://user-images.githubusercontent.com/40642407/46387098-f6472400-c679-11e8-8c73-ded9269ab800.png">

**Comment by annagree** [comment]
Same with this click through page: 
<img width="999" alt="screen shot 2018-10-02 at 3 55 02 pm" src="https://user-images.githubusercontent.com/40642407/46387118-11199880-c67a-11e8-883f-ebf1f8403ad6.png">

**Comment by stockards** [comment]
This is super helpful thanks @annagree ! I'll be working on this likely tomorrow.

**Comment by stockards** [comment]
Ready for review 
<img width="570" alt="screen shot 2018-10-04 at 12 00 29 pm" src="https://user-images.githubusercontent.com/38479289/46496527-22bf8500-c7cd-11e8-93f1-106282da622d.png">

**Comment by annagree** [comment]
@gatof81 Can you update the arrows in the Network widget (Tissue Specificity of Gene Connections) and in the gene-brainregions pages? 
They should be colons now instead of arrows, as per Stockard's designs.
