### ISSUE TITLE
all components have expected behavior with missing data

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#344]
Each widget needs the ability to handle missing data independently. 
While we are waiting for the design, we can use a placeholder of text that says "no data" when the plot or text field is not available.

**Comment by annagree** [comment]
Related to #331

**Comment by Zaknarfen** [comment]
Is there a way, currently, to route to a missing data gene? Can you guys give me one gene to test this? For people typing a gene id that is not in the database, the application should redirect to the `/genes` route page.

**Comment by kdaily** [comment]
Working on it right now! There isn't currently a gene in our data that is missing, as everything is pre-filtered to be consistent. I will have to push a new data version in order to test it.

**Comment by kdaily** [comment]
I think version 6 of the data should have this.

**Comment by kdaily** [comment]
http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000223972) as an example.

**Comment by kdaily** [comment]
An example of a nominated target that should have a page is `IL10`:

http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000136634)

**Comment by Zaknarfen** [comment]
I believe there is a huge condition to prevent loading missing data and redirecting to the `genes` page. I need to remove that and test it out here.

**Comment by Zaknarfen** [comment]
First draft for the box plot is this:

![image](https://user-images.githubusercontent.com/4223973/44421396-c4a94c00-a556-11e8-9368-a372dcdacf87.png)

I also added a text in the case of missing data for the `Summary of Evidence` part. When we don't have the information i put `No data` (where those `True/False` ones are).

**Comment by Zaknarfen** [comment]
I followed @stockards design in Figma and changed the placeholders to the same gray color. The new placeholder is already in the Agora website. Just search for IL10 (some charts are still broken for missing data, median and network).

**Comment by annagree** [comment]
Network and Median Expression plots still need to be updated

**Comment by annagree** [comment]
See #331 for details on design.
