### ISSUE TITLE
need design for filtering of network widget

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#346]

**Comment by stockards** [comment]
What are the filtering options? Are we looking to filter them by the following attached?
<img width="753" alt="screen shot 2018-08-22 at 10 32 53 am" src="https://user-images.githubusercontent.com/38479289/44479900-c0347000-a5f6-11e8-8cc5-e669b25618dc.png">

**Comment by annagree** [comment]
@stockards to design drop down.

Label: Number of brain regions [need better text here]
Values: 1, 2, 3, 4, 5, 6

**Comment by stockards** [comment]
After doing a couple options, I think the slider may work best for this. Please let me know if you have any questions. Files also in Figma. 

<img width="780" alt="screen shot 2018-08-23 at 3 33 51 pm" src="https://user-images.githubusercontent.com/38479289/44555442-1209f280-a6ea-11e8-82f2-ae61ab56bef0.png">

**Comment by kdaily** [comment]
Thanks @stockards! One change would be the left side "<1" - that should be "1>". Otherwise looks like it's less than one.

**Comment by kdaily** [comment]
Oh I see what you're doing. I think we want the logic the other way - selecting a number filters edges with at least that number. It's a "select edges with more than" not a "filter edges with less than".

**Comment by annagree** [comment]
Oooh I like this. 
@blogsdon can you figure out a better label than "Filter by number of brain regions"?

**Comment by stockards** [comment]
Oops fixed! Let me know once the labels are solidified and the logic. Happy to talk it through tomorrow as well, I'll be in the office. :)

**Comment by annagree** [comment]
@annagree update text and create content for info modal in Figma

**Comment by annagree** [comment]
@stockards see comments in Figma. We will need to add one more category to the slider. Also need design for placement of info modal.
