### ISSUE TITLE
create test data for missing gene handling

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#347]
Data should include one gene that is missing all RNA-seq data but has at least some of the "Summary of Evidence" fields.

**Comment by annagree** [comment]
@kdaily once you have the data available, please let Diego and Renan know where it is and which gene they can use for testing

**Comment by annagree** [comment]
current blocker for issue #331

**Comment by kdaily** [comment]
Version 6 of the data has this. Here's an example:

http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000223972)
