### ISSUE TITLE
get a staging server up

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#350]
We need a live, accessible version of the site for testing and validation. Running the stack locally prior to releasing on the live site is not a sustainable solution.

This will include:

1. Get IT to set up an AWS EC2 (current) or ECS deployment (future) for a staging site. (https://sagebionetworks.jira.com/browse/IT-310)
1. Process to deploy `develop` branch to the staging server
1. Process to evaluate the staging version prior to a production release
1. Release the `master` branch to production once we're satisfied

**Comment by zaro0508** [comment]
This is done.  there are now 3 environments.
https://agora-develop.ampadscicomp.org/genes
https://agora-staging.ampadscicomp.org/genes
https://agora-prod.ampadscicomp.org/genes
