### ISSUE TITLE
hero text on nominated target info page is empty

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#351]
![screenshot from 2018-08-22 16-04-50](https://user-images.githubusercontent.com/84993/44495548-2d5efa00-a625-11e8-93bb-76c99b35d7fa.png)

**Comment by Zaknarfen** [comment]
I think I know what it is.

**Comment by Zaknarfen** [comment]
I fixed this in this last commit. You can also just run `npm run docker` now @kdaily, it includes a clean script now for `Docker`. Hopefully free of duplicated data.
