### ISSUE TITLE
need agora unavailable when down, restarting, etc

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#352]
Tried to load a few min ago, think @Zaknarfen is restarting the server to take care of duplicates. I get the standard `ERR_CONNECTION_REFUSED` browser page. We need a redirect for 400, 500, 503, or other error codes that indicates Agora is down, potentially redirects to ampadportal.org.

![screenshot from 2018-08-23 10-42-28](https://user-images.githubusercontent.com/84993/44542305-41583980-a6c1-11e8-8a68-41b74bc1f32a.png)

**Comment by annagree** [comment]
duplicate issue- closing
