### ISSUE TITLE
any numbers on plots or text should be 2 significant digits 

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#354]
This should be done on the front end, not in the underlying data.

**Comment by annagree** [comment]
Anna to detail which elements are impacted and need to be updated.

**Comment by annagree** [comment]
see comments in issue #249

**Comment by Zaknarfen** [comment]
@annagree can you point me to the other places where this happens? Forest plot is done I believe.

**Comment by annagree** [comment]
Two places to fix are the hover-over boxes for the Box plot and the forest plot 

Attaching screen shots.
<img width="1440" alt="screen shot 2018-08-31 at 3 26 20 pm" src="https://user-images.githubusercontent.com/40642407/44938304-efec2200-ad32-11e8-86cf-af4809f5194f.png">
<img width="1440" alt="screen shot 2018-08-31 at 3 26 14 pm" src="https://user-images.githubusercontent.com/40642407/44938307-f7133000-ad32-11e8-9dd1-1fc75e36a28d.png">

**Comment by annagree** [comment]
I am not able to verify whether the Median Expression plot is impacted, as there is currently a bug where it is not showing. See #362. Please don't close issue until we are able to verify.

**Comment by Zaknarfen** [comment]
I have fixed all the place where it occurs. I've already fixed this in the median chart also (had the same problems you showed here). I took the opportunity and made the median chart more close to what the design shows, remade the scaling, fonts, width of the bars, and colors. I am going to merge these changes soon.

**Comment by annagree** [comment]
Great!
