### ISSUE TITLE
set up agora in AWS ECS

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#360]
A Sage engineer (@zaro0508) has started a Cloud Formation configuration for getting our app inside ECS:

https://github.com/Sage-Bionetworks/sandbox-infra/blob/master/templates/agora.yaml

We need to work on replacing the `Task` section of this:

https://github.com/Sage-Bionetworks/sandbox-infra/blob/master/templates/agora.yaml#L89-L132

Looks like this will entail getting our script that pulls the data (`npm run data:aws`) and that starts up the server (`npm run docker`) into the appropriate ECS task definition framework.

**Comment by kdaily** [comment]
Jira issue: https://sagebionetworks.jira.com/browse/IT-292

**Comment by zaro0508** [comment]
We have decided to ditch docker in favor of deploying to elastic beanstalk.  We decided that docker added additional overhead but did not provide any additional value over beanstalk.  Especially when we only care to deploy to a single cloud, AWS.   The beanstalk environments have been setup as indicated by issue https://github.com/Sage-Bionetworks/Agora/issues/337

**Comment by zaro0508** [comment]
We have decided to ditch docker so no need for ECS.  We decided that docker added additional overhead without providing additional value over beanstalk.  Especially when we only care to deploy to a single cloud, AWS.  Agora has been deploy to beanstalk per issue https://github.com/Sage-Bionetworks/Agora/issues/360
