### ISSUE TITLE
transform druggability data

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#361]
Create MongoDB from Druggability data in Synapse.

**Comment by annagree** [comment]
@blogsdon 
First fix typo in file for Druggability Classification for the below genes. Change from "targetable, **strucutrally** enabled" to "targetable, **structurally** enabled"

ENSG00000006125
ENSG00000153046
ENSG00000105398
ENSG00000162433
ENSG00000164050

**Comment by annagree** [comment]
@annagree to update the file.

**Comment by annagree** [comment]
New version has been uploaded to Synapse.
@kdaily  to ensure it is mergeable with current data. Decide where/how to integrate data.

**Comment by annagree** [comment]
Tables in Agora synapse folder contain expected terms.

**Comment by annagree** [comment]
@kdaily Wanted to check in on progress here- do you think this can be done on Thursday so we can prioritize the development of the new widgets Stockard has designed?

**Comment by annagree** [comment]
Ensembl ID for NEFL in druggability file has been updated to match that used in the rest of the site. @kdaily you should be good to go!

**Comment by kdaily** [comment]
version 8 of the data has the druggability added: https://www.synapse.org/#!Synapse:syn13363290.8

This version updates the `gene_info.json` file to this one: https://www.synapse.org/#!Synapse:syn12548902.19
