### ISSUE TITLE
median expression plot is not currently visible

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#362]
Definitely should be visible for VGF, as there is data for all the points in the median expression plot: 

<img width="1268" alt="screen shot 2018-08-31 at 3 34 23 pm" src="https://user-images.githubusercontent.com/40642407/44938410-abad5180-ad33-11e8-9426-8609c44f6947.png">

**Comment by kdaily** [comment]
Somehow between version 16 and 17 of `geneInfo.json` that data was not added.

**Comment by kdaily** [comment]
Version 7 (https://www.synapse.org/#!Synapse:syn13363290.7) has this fixed.

`package.json` data version is currently wrong, though - listed as 5 but we are using 6 on the live site.

**Comment by annagree** [comment]
@Zaknarfen  to Update data versions and push live.

**Comment by Zaknarfen** [comment]
The new version is live, we can close this.
