### ISSUE TITLE
design for message for non-supported browsers

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#370]
Need design and customized message that will pop-up when a browser does not support figure downloads.

**Comment by stockards** [comment]
Taking feedback and welcoming final content! :) 
<img width="595" alt="screen shot 2018-09-19 at 2 04 38 pm" src="https://user-images.githubusercontent.com/38479289/45781491-fb858700-bc14-11e8-97da-887b1865e8e8.png">

**Comment by annagree** [comment]
Looks good to me! Ready for development, assuming we keep the download feature.

**Comment by stockards** [comment]
Where is the status on this one @annagree ?

**Comment by annagree** [comment]
@Zaknarfen Do we have this error message implemented yet?

**Comment by Zaknarfen** [comment]
@annagree I was thinking about this. It might be better to show a message for users to update their browsers when using our website. That would probably be better than this popup message when downloading. In case users have old browsers or not supported ones, we can direct them to it and the download should always work.

**Comment by Zaknarfen** [comment]
@annagree and @stockards I added `browser-update` as a package to the project, so anyone with a browser outside our requirements gets a popup:

![image](https://user-images.githubusercontent.com/4223973/52364869-64876300-2a2d-11e9-937d-2ebcbbff5e9e.png)

We can change the position of this popup and styling.

**Comment by annagree** [comment]
@Zaknarfen let's discuss this in standup this week
