### ISSUE TITLE
establish data testing

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#371]
use JSON schema file to check data

**Comment by kdaily** [comment]
See for an example: https://github.com/opentargets/json_schema/tree/master/src/evidence

**Comment by kdaily** [comment]
https://github.com/Sage-Bionetworks/agora-data-schemas as a first pass.

**Comment by annagree** [comment]
@kdaily I'm moving all issues unrelated to front-end web dev to Jira. Would you please translate this into a new issue in SCIENCE as needed?

**Comment by kdaily** [comment]
Can do!
