### ISSUE TITLE
nominated target supporting data and analyses

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#376]
Need plan for how data will be structured.

**Comment by kdaily** [comment]
This is related to #371 regarding a data model or schema that describes target and evidence relationships.

I would say more important for submitted evidence than our current information display to have a mechanism for this.

See for an example: https://github.com/opentargets/json_schema/tree/master/src/evidence

**Comment by annagree** [comment]
Overview of supporting evidence:
https://docs.google.com/spreadsheets/d/13d7Ry6rbcBlO_tmIWCNB-LoFsaxyQfXDaqNrsnB1oX0/edit?usp=sharing

Overall plan detailed here:
https://docs.google.com/document/d/1WQ03ye22vGGgWOnFGco4AplW7XOLZWptl1t2PEMi_Zw/edit?usp=sharing
