### ISSUE TITLE
Add error handling in the backend

### ISSUE THREAD

**Issue by Zaknarfen** [Sage-Bionetworks/Agora#38]

**Comment by kdaily** [comment]
@Zaknarfen is this done?

**Comment by annagree** [comment]
Need design for error pages.

**Comment by annagree** [comment]
Errors should be consistent. Could go to homepage but show a pop-up window?

**Comment by annagree** [comment]
@Zaknarfen Please add error messages to this so Stockard has content for design.

**Comment by annagree** [comment]
Would be similar to 404 error page, with customized error message.

**Comment by stockards** [comment]
Initial layout is done but will need to know what the various error states are to ensure that they all work within the page and it's the right solution.
![error page](https://user-images.githubusercontent.com/38479289/49476348-98949c80-f7ce-11e8-85b9-10604b7b5441.png)

**Comment by annagree** [comment]
@gatof81 @Zaknarfen Stockard has created a page- please comment if this will work or if we need something else.

**Comment by Zaknarfen** [comment]
Yes, it is. we can close this. That error page will only show up on an invalid redirection from the router (invalid route). I left the message as `404`, page not found. The other errors are being thrown as popups in small dialog boxes.
