### ISSUE TITLE
Update "Druggability" text under Summary of Evidence

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#381]
For **Druggability**, 
It currently says:  _Coming soon_
please replace with:  _See "Next Steps" at bottom of page_

<img width="925" alt="screen shot 2018-09-19 at 10 53 24 am" src="https://user-images.githubusercontent.com/40642407/45771637-7beabe80-bbfa-11e8-81a4-894dbd9f5ca5.png">

**Comment by annagree** [comment]
Also add direct link to bottom of page.

**Comment by Zaknarfen** [comment]
@annagree the modal also shows coming soon, what do I add there?

**Comment by annagree** [comment]
Anna needs to update the modal content.
