### ISSUE TITLE
HOME PAGE: Spacing within Nominated Targets Tile 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#382]
When resized the kerning (spacing) between the letters seems to change. This only seems to be happening on the Nominated Targets tile for some reason.
<img width="1220" alt="screen shot 2018-09-19 at 2 12 47 pm" src="https://user-images.githubusercontent.com/38479289/45781908-3dfb9380-bc16-11e8-93b4-14ec4a9bfd0e.png">

**Comment by annagree** [comment]
make text unjustified

**Comment by Zaknarfen** [comment]
We can close this now, re-open if the issue persists.
