### ISSUE TITLE
HOME PAGE: Gene not listed modal

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#383]
Modal does not following the styling within Figma. I have attached both the current version and what it should look like. 
<img width="368" alt="screen shot 2018-09-19 at 2 15 06 pm" src="https://user-images.githubusercontent.com/38479289/45782135-d72aaa00-bc16-11e8-8594-5c9b4511c3e4.png">
<img width="593" alt="screen shot 2018-09-19 at 2 18 00 pm" src="https://user-images.githubusercontent.com/38479289/45782137-d72aaa00-bc16-11e8-8478-933399f0ef10.png">

**Comment by Zaknarfen** [comment]
We can close this now, re-open if the issue persists.
