### ISSUE TITLE
NOMINATED TARGETS: Gene Filter Content

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#384]
We are looking to get some more insight into the phrasing behind the gene filter hint text. There has already been some suggestions on it within the Home page. Keep this as an issue because we may want to change this in the coming week.
<img width="1188" alt="screen shot 2018-09-19 at 2 20 09 pm" src="https://user-images.githubusercontent.com/38479289/45782303-51f3c500-bc17-11e8-9699-d63ef85fcf80.png">

**Comment by annagree** [comment]
no longer relevant
