### ISSUE TITLE
TARGET PAGE: AMP-AD Nominated button

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#386]
Items are not center aligned within the AMP-AD Nominated button.
<img width="383" alt="screen shot 2018-09-19 at 2 24 45 pm" src="https://user-images.githubusercontent.com/38479289/45782456-d9413880-bc17-11e8-92be-30b10bc3e2df.png">

**Comment by annagree** [comment]
export as image from Figma, rather than relying on text.
