### ISSUE TITLE
TARGET PAGE: Summary of Evidence Modal doesn't match styling

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#388]
Summary of Evidence information modal does not match the Figma styling. Please see attached for current site vs. Figma. 
<img width="600" alt="screen shot 2018-09-19 at 2 29 33 pm" src="https://user-images.githubusercontent.com/38479289/45782700-8d42c380-bc18-11e8-86ea-0ec068f64eb5.png">
<img width="1007" alt="screen shot 2018-09-19 at 2 29 38 pm" src="https://user-images.githubusercontent.com/38479289/45782701-8ddb5a00-bc18-11e8-9b14-71c1b4ca0e04.png">

**Comment by annagree** [comment]
@stockards please verify and close if done.
