### ISSUE TITLE
WIDGETS: Expand Symbol Distorted

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#389]
Expand symbol is distorted for some reason. See Figma if you need to grab the symbol itself or reach out to me for it.
<img width="1218" alt="screen shot 2018-09-19 at 2 31 05 pm" src="https://user-images.githubusercontent.com/38479289/45782768-bd8a6200-bc18-11e8-8f28-24b13ba0e149.png">

**Comment by annagree** [comment]
@stockards please verify and close if done.
