### ISSUE TITLE
DOWNLOAD: Modal

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#390]
---Hold on this but looking to brain storm---

Already in feedback it seems that downloading as a PNG may not be helpful. We should talk more about this feature and how we can better it. :)

**Comment by annagree** [comment]
@stockards Would love to bring this back up to the list of things to discuss. Both whether the graph is useful at all, but more tangibly the modal itself is not working effectively right now, and would love to talk thru some possible tweaks.

**Comment by stockards** [comment]
@annagree I just sent you an invite, let's talk about this and any needs this Friday. :)

**Comment by annagree** [comment]
@Zaknarfen Can we hide the download icons for figures for now?
