### ISSUE TITLE
DOWNLOAD: Check box

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#391]
Check box is a different color if you unselect and reselect it. Make these consistent with the initial check box color (teal).
<img width="314" alt="screen shot 2018-09-19 at 2 32 53 pm" src="https://user-images.githubusercontent.com/38479289/45782999-6638c180-bc19-11e8-80e8-d15eeb268562.png">
<img width="315" alt="screen shot 2018-09-19 at 2 36 23 pm" src="https://user-images.githubusercontent.com/38479289/45783000-6638c180-bc19-11e8-98a0-8f1526d1d761.png">

**Comment by annagree** [comment]
@stockards please validate and close if done.
