### ISSUE TITLE
BRAIN TISSUES MODAL: Styling doesn't match Figma

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#392]
Styling doesn't match Figma for this. @annagree was there a want to bring back the brain region illustrations here?

<img width="1004" alt="screen shot 2018-09-19 at 2 36 52 pm" src="https://user-images.githubusercontent.com/38479289/45783128-c62f6800-bc19-11e8-9854-00d48c88d5e8.png">
<img width="579" alt="screen shot 2018-09-19 at 2 38 49 pm" src="https://user-images.githubusercontent.com/38479289/45783129-c62f6800-bc19-11e8-92f1-dea28fdbad62.png">

**Comment by annagree** [comment]
I think we can skip the brain regions part for now. Let's focus on making consistent with Figma.

**Comment by Zaknarfen** [comment]
I think this is correct already, can we close this? @annagree @stockards
