### ISSUE TITLE
OVERALL EXPRESSION CHART: Clickability

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#393]
<img width="1103" alt="screen shot 2018-09-19 at 2 43 14 pm" src="https://user-images.githubusercontent.com/38479289/45783342-5c638e00-bc1a-11e8-92a1-36f49c19ac56.png">
There is no benefit to this being clickable. Is there a reason why it was created to be clickable? If not, please eliminate this feature.

**Comment by Zaknarfen** [comment]
I think this was done by @gatof81 already.

**Comment by annagree** [comment]
Done.
