### ISSUE TITLE
DIFFERENTIAL EXPRESSION FILTER: Check boxes

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#394]
Check boxes are not styled correctly. Please refer to the others on the site (such as Download) for how they should look. 
<img width="765" alt="screen shot 2018-09-19 at 2 43 49 pm" src="https://user-images.githubusercontent.com/38479289/45783416-8b79ff80-bc1a-11e8-9237-28538de1c575.png">
<img width="315" alt="screen shot 2018-09-19 at 2 36 23 pm" src="https://user-images.githubusercontent.com/38479289/45783421-90d74a00-bc1a-11e8-82e1-ea34c279eae0.png">

**Comment by Zaknarfen** [comment]
I think this is correct already, can we close this? @annagree @stockards
