### ISSUE TITLE
LOG FOLD CHANGE: Font styling

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#395]
Styling should match the chart below "Consistency of Change in Expression ".
<img width="358" alt="screen shot 2018-09-19 at 2 46 24 pm" src="https://user-images.githubusercontent.com/38479289/45783527-dd228a00-bc1a-11e8-93d5-a9458eef6481.png">
<img width="989" alt="screen shot 2018-09-19 at 2 46 52 pm" src="https://user-images.githubusercontent.com/38479289/45783528-dd228a00-bc1a-11e8-948b-6d8723dde5b5.png">

**Comment by Zaknarfen** [comment]
In this case, would this be just the color for the `log 2 fold change` text? Or should I capitalize it too? @stockards @annagree

**Comment by annagree** [comment]
@stockards please verify change and go ahead and close if resolved.

**Comment by stockards** [comment]
Capitalize "log fold change" within the Consistency of Change in Expression chart for consistency.

**Comment by annagree** [comment]
resolved
