### ISSUE TITLE
NETWORK WIDGET: Filter Styling

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#396]
Styling doesn't match Figma comps.
<img width="756" alt="screen shot 2018-09-19 at 2 48 10 pm" src="https://user-images.githubusercontent.com/38479289/45783642-3094d800-bc1b-11e8-809f-1e81e3778e17.png">
<img width="787" alt="screen shot 2018-09-19 at 2 48 16 pm" src="https://user-images.githubusercontent.com/38479289/45783644-312d6e80-bc1b-11e8-809a-58ebe3485f9d.png">

**Comment by annagree** [comment]
Top is the Figma design.

**Comment by diegotoptal** [comment]
Ready

**Comment by annagree** [comment]
@stockards please verify and close if this is done.
