### ISSUE TITLE
NETWORK WIDGET: Move up network

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#397]
We have been getting feedback that people can not see the network. Is this possible to move it up in the space so they can see it when they are seeing the filter?
<img width="815" alt="screen shot 2018-09-19 at 2 49 54 pm" src="https://user-images.githubusercontent.com/38479289/45783709-6b970b80-bc1b-11e8-97da-a28717712c9b.png">

**Comment by annagree** [comment]
@stockards to try to replicate this and get more information about when this occurs.

**Comment by annagree** [comment]
might be related to column width

**Comment by diegotoptal** [comment]
![screen shot 2018-09-21 at 16 02 57](https://user-images.githubusercontent.com/24323365/45901042-eb59dd00-bdb7-11e8-8f63-9d9fd9e47fcf.png)

![screen shot 2018-09-21 at 15 38 40](https://user-images.githubusercontent.com/24323365/45900736-f6f8d400-bdb6-11e8-96c2-dc1d216fe39a.png)
![screen shot 2018-09-21 at 15 38 21](https://user-images.githubusercontent.com/24323365/45900737-f6f8d400-bdb6-11e8-81c4-2c33b2818ab4.png)

those are the worst case scenarios for screens which with it's between 700px - 1024px width, the report might be from before the latest fix.

below that width, the responsive layout pushes the left column to the bottom and the height of the network is reset to 500px.

above 1024px the left column height becomes a lot shorter and the network widget looks good.

**Comment by diegotoptal** [comment]
@annagree @stockards any suggestions on how to proceed?

**Comment by diegotoptal** [comment]
I had changed the responsiveness to anything below 1200px will move the left column to down the network widget to avoid issues with this column been to narrow and long.

so the smallest screen that will get two columns will be 1280x720 and up.
![screen shot 2018-09-24 at 17 57 10](https://user-images.githubusercontent.com/24323365/45978767-7e4a7f80-c023-11e8-91c6-965e6d5c4ef9.png)

anything below this will show only the network widget and all the information below it. 

@annagree what do you think?
