### ISSUE TITLE
Review Submit Form

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#408]
I am still working on where we will place the button for users to be able to submit their information. Please take a look at this per our discussion for thoughts and feedback. Thanks!
![submit form](https://user-images.githubusercontent.com/38479289/46033416-0035b980-c0b3-11e8-96f7-a6d755315a33.png)

**Comment by karawoo** [comment]
I'm not sure I'm clear on the distinction between analyses and methods. I wonder if it could be one question -- "do you have analyses or methods that you are prepared to share in support of the nomination?" (also there's a typo in the question as written (nominiation)).

**Comment by stockards** [comment]
@annagree Do you have thoughts on the phrasing? I just placed in the questions which we articulated from our meeting but happy to adjust as needed.

**Comment by annagree** [comment]
@stockards Yes- after seeing it this way, I agree with @karawoo. Let's combine these into one, and maybe change from analyses to data: 
Do you have data and methods that you are prepared to share in support of the nomination?

**Comment by annagree** [comment]
@stockards Once we figure out where to place this, we should update the title as well. We can discuss later- this is just a note to make sure I remember to revisit it.

**Comment by stockards** [comment]
@annagree Did you decide on an update for the title by any chance? I forgot to ask, thanks!
