### ISSUE TITLE
new summary box for druggability information

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#411]
See figma designs here:
https://www.figma.com/file/RAV7geFcRz1qvNjk4XFxRKk6/Agora?node-id=1911%3A0
"Small Molecule Druggability Information"

**Comment by annagree** [comment]
Requires completion of #361

**Comment by annagree** [comment]
Version 8 of data has druggability information. Please follow figma designs referenced above, and build a new druggability summary section using the data. 

For some genes, there is no druggability information in the file. For such genes, please indicate: Data not available

**Comment by Zaknarfen** [comment]
I just updated the data to the latest version at the AWS machine. The new summary is being made.

**Comment by annagree** [comment]
This is done.
