### ISSUE TITLE
add visual feedback to gene search

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#413]
Add spinner to provide feedback to users when they are typing slowly in gene search box

@Zaknarfen please tag Stockard if you need a design here.

**Comment by annagree** [comment]
@stockards Can you look at this new spinner and see what you think?

**Comment by stockards** [comment]
Please make color #5171C0.

**Comment by annagree** [comment]
@stockards can you please validate the color and close if fixed?

**Comment by annagree** [comment]
Here's what I see on my monitor:
<img width="1198" alt="screen shot 2018-10-15 at 1 18 09 pm" src="https://user-images.githubusercontent.com/40642407/46975991-f9301480-d07c-11e8-8d40-8c48cd1591e9.png">

**Comment by Zaknarfen** [comment]
Closing this as fixed.
