### ISSUE TITLE
Edit line length within RNA-Seq Differential Expression section

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#428]
There was some feedback about the lines going all the way to the end within this section and it looking separate. Try having it begin on the left hand side where the content starts, and extend off of the right hand side of the screen. 
<img width="672" alt="screen shot 2018-10-02 at 1 36 21 pm" src="https://user-images.githubusercontent.com/38479289/46375526-84a2b200-c648-11e8-92b7-b227ee22a345.png">

**Comment by Zaknarfen** [comment]
This is done we can close it.
