### ISSUE TITLE
Teams list order should be alphabetical 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#435]
http://agora.ampadportal.org/teams-contributing

**Comment by kdaily** [comment]
Huh! It is except for Duke. I'll look in the data.

**Comment by stockards** [comment]
I know, weird right!? When we were going through the user interview yesterday I noticed it. Thanks!

**Comment by Zaknarfen** [comment]
They are loading asynchronously now, so teams with smaller images in total load faster (the order is not guaranteed). That is why it doesn't show in alphabetical order. I'll try to change them after they all load perhaps?

**Comment by Zaknarfen** [comment]
Should be fixed, we can close this. Let me know if we need custom ordering or something, or re-open if this is still incorrect.
