### ISSUE TITLE
network widget not updating as expected after selecting neighbor gene

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#436]
The content is not updating as expected after selecting a new gene within the interactive network widget. For example, from the network within VGF, if I select SYT12 I expect to see information for SYT12 in the Gene info box, the Tissue Specificity of Gene connections box, and the Similar Genes box. The Gene info box updates, but only one gene is visible in the Tissue Specificity of Gene connections box and the Similar Genes box. See screen shot: 
<img width="1410" alt="screen shot 2018-10-08 at 9 39 46 am" src="https://user-images.githubusercontent.com/40642407/46622327-037f6b00-cadf-11e8-9331-d2e6d454f6bc.png">

**Comment by annagree** [comment]
If I then click on the Filter ">0" it seems to reset and then it is updated correctly showing more than one listing in the Tissue Specificity of Gene connections box and the Similar Genes box.
<img width="1421" alt="screen shot 2018-10-08 at 9 48 18 am" src="https://user-images.githubusercontent.com/40642407/46622411-4f321480-cadf-11e8-8b4a-994e0cfb2fbf.png">

**Comment by annagree** [comment]
@gatof81 Please comment if you need more information on this, it's a bit hard to describe, so hopefully you can try to replicate it yourself.

**Comment by gatof81** [comment]
I can detect some console errors and some miss behavior that is hard to explain, I'll fix it and make sure it works properly and we can check later on if it works as expected.
