### ISSUE TITLE
Navigation doesn't align like it does in Figma

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#443]
Margin should be the same as from the left side w/ the Agora logo.

**Comment by annagree** [comment]
@Zaknarfen Increase margin size on right side of navigation menu to match left side, as per Figma.

Current site:
<img width="1575" alt="screen shot 2018-11-26 at 10 56 30 am" src="https://user-images.githubusercontent.com/40642407/49035654-46b69b80-f16a-11e8-8650-00a336a63168.png">

**Comment by Zaknarfen** [comment]
I think staging is already correct now, I'll close this, re-open if it persists.
