### ISSUE TITLE
All current purple headers and gene names within colored headers can be changed to #3F5EAB

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#450]
The Figma file has this updated in it. The current header for the home page, nominated targets is purple but I made it one shade darker so in the smaller size it will pass contrast accessibility. Please make the gene names on the gene detail pages as well as the headers listed above 3F5EAB.

**Comment by Zaknarfen** [comment]
I think this is done. Re-open if not @stockards.
