### ISSUE TITLE
Team photos are incorrectly assigned on contributing teams page

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#466]
I know that at least MSSM and Mayo-UFL-ISB team photos appear to be switched on the team page. Strangely they are OK on the nomination details pages.

Correct:
<img width="1217" alt="screen shot 2018-10-21 at 3 24 28 pm" src="https://user-images.githubusercontent.com/40642407/47273200-7fe56580-d545-11e8-8a59-822b07b71688.png">

**Comment by amapeters** [comment]
@gatof81 - has this been pushed to production?

**Comment by annagree** [comment]
@amapeters not yet. Do you see anything wrong other than MSSM and Mayo?

**Comment by amapeters** [comment]
Not other than those, but we should see if photos are available where missing

**Comment by gatof81** [comment]
no, It have just been push to development, on next update will be able to
check it out on production.
