### ISSUE TITLE
Nominate Target List: Selection should be same color as it is on home page 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#479]
<img width="533" alt="screen shot 2018-10-24 at 11 03 45 am" src="https://user-images.githubusercontent.com/38479289/47451371-6e39d300-d77c-11e8-8f50-c1ef13a981de.png">

**Comment by gatof81** [comment]
@stockards do the hover of the list need to be the same color as the drop-down hover on the homepage?
