### ISSUE TITLE
make simple descriptions of studies

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#48]
We need short, descriptive paragraphs of the salient details of the studies in use in the Wall of Targets (`ROSMAP`, `MSBB`, and `MayoRNAseq`).

I've updated this Synapse table (https://www.synapse.org/#!Synapse:syn11363298/) with a long name and description text that is from the Folder Wiki for each study. However this is likely too much or the wrong details.

**Comment by annagree** [comment]
This update will happen when portal is updated.
