### ISSUE TITLE
do not require HGNC symbols in network data

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#482]
We currently provide `geneA_external_gene_name` and `geneB_external_gene_name` as properties of a network edge. This requires some data processing code to add (by looking in the data provided in `gene_info.json` effectively). It would be great if we could remove this and always get the current symbols from the `hgnc_symbol` field in `gene_info.json` given an `ensembl_gene_id`.

So, instead of a record that looks like:

```
{
    "geneA_ensembl_gene_id": "ENSG00000268903",
    "geneB_ensembl_gene_id": "ENSG00000150337",
    "brainRegion": "DLPFC",
    "geneA_external_gene_name": "AL627309.6",
    "geneB_external_gene_name": "FCGR1A"
  }
```

It would be:

```
{
    "geneA_ensembl_gene_id": "ENSG00000268903",
    "geneB_ensembl_gene_id": "ENSG00000150337",
    "brainRegion": "DLPFC"
  }
```

The gene symbols could be looked up from `gene_info.json` by Ensembl ID fields in the network record. I would still be doing validation on the edges existence in the appropriate data sources.

**Comment by annagree** [comment]
Moved to Jira
