### ISSUE TITLE
remove escape characters before quote

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#485]
Throughout the site, there are now escape characters ( \ ) visible before most apostrophes. These should be removed. E.g:

<img width="1022" alt="screen shot 2018-10-25 at 9 52 52 am" src="https://user-images.githubusercontent.com/40642407/47517117-12368380-d83c-11e8-981c-976952c58921.png">

**Comment by annagree** [comment]
@annagree will make a full inventory later.

**Comment by Zaknarfen** [comment]
@diegotoptal did this already.
