### ISSUE TITLE
Evidence tab: part of graph is cut off

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#489]
[VGF](http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000128564)) - part of the red dot is cut off on the graph

<img width="1354" alt="screen shot 2018-10-25 at 1 10 13 pm" src="https://user-images.githubusercontent.com/4452678/47527506-8599be80-d857-11e8-9224-d672950d23f5.png">

**Comment by karawoo** [comment]
Also in the next plot:

<img width="1285" alt="screen shot 2018-10-25 at 1 12 22 pm" src="https://user-images.githubusercontent.com/4452678/47527562-a530e700-d857-11e8-9549-a8270d1e2fa4.png">

**Comment by Zaknarfen** [comment]
I think this is fixed already. Re-open if it isn't.
