### ISSUE TITLE
improve names of downloaded pngs

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#496]
for median expression, the name is `overall_exp_ac_tissues.png`. Not very informative.

**Comment by Zaknarfen** [comment]
Sure, I will change to that.

**Comment by annagree** [comment]
@Zaknarfen Yes- it would be ideal to also include the name of the plot along with the Gene name.
Let's use:
GeneName Overall Expression
GeneName Differential Expression_statisticalmodelname
GeneName Forest Plot_statisticalmodelname

Make sense?

**Comment by Zaknarfen** [comment]
I'll leave a preview image of how it looks here with the changes and close this issue as fixed.

![file_names](https://user-images.githubusercontent.com/4223973/49159800-6e456980-f30c-11e8-8ba6-bf15d7209277.jpg)
