### ISSUE TITLE
pngs have transparent background

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#500]
at least the overall expression bar chart does. I think most people will expect a white background.

**Comment by annagree** [comment]
Should be white background with grey axes lines, similar to display on website. Currently they are transparent with white axes (at least on Chrome on Macbook):

![consistency_chg_in_exp 2](https://user-images.githubusercontent.com/40642407/48363376-9cfbe880-e65a-11e8-8207-a60415c4839f.png)

**Comment by annagree** [comment]
^^ it actually looks OK when pasted here, but the PNG itself looks odd.
