### ISSUE TITLE
Remove line - nominated targets

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/Agora#506]
http://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000179632)

Remove the extra line at the bottom of the page

<img width="478" alt="screen shot 2018-10-25 at 1 35 30 pm" src="https://user-images.githubusercontent.com/2660103/47528805-fbebf000-d85a-11e8-8fd3-135232cc1008.png">

**Comment by annagree** [comment]
@stockards Can you advise on preferred layout at the end of the nomination details page? Renan wasn't sure if he should have an extra line after the last entry.

**Comment by stockards** [comment]
This is in the Figma file.

**Comment by annagree** [comment]
@gatof81 See the updated screenshot. This relates to the Nomination Details tab. The dividers should only be in between the different teams, should remove the extra divider line at the bottom.
<img width="1352" alt="screen shot 2018-12-04 at 2 09 28 pm" src="https://user-images.githubusercontent.com/40642407/49476345-90d4f800-f7ce-11e8-9ba9-469ca8591f67.png">
