### ISSUE TITLE
scrolling below about, help, terms & privacy

### ISSUE THREAD

**Issue by blogsdon** [Sage-Bionetworks/Agora#509]
<img width="1128" alt="screen shot 2018-10-25 at 1 38 42 pm" src="https://user-images.githubusercontent.com/1447157/47529018-82083680-d85b-11e8-849f-4bcae29dfcb8.png">

**Comment by blogsdon** [comment]
probably not expected behavior?

**Comment by annagree** [comment]
Should not be possible to scroll below the footer.
