### ISSUE TITLE
Text lines are really long on large monitors

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#512]
I don't have a screenshot that captures this well right now because I'm on my laptop, but I've noticed that lines of text (for example on the [about page](http://agora.ampadportal.org/about)) are quite long, and on large monitors they're hard to read because they're so long.

**Comment by annagree** [comment]
@stockards Any thoughts on this issue?

**Comment by stockards** [comment]
@Zaknarfen @diegof18 What is the current number of characters per line? Could we try a max of 80 and see what that looks like so this is not an issue?

**Comment by annagree** [comment]
@diegof18 see above- please try implementing a max of 80 characters per line and see how this looks on staging.

**Comment by gatof81** [comment]
I implement an 80ch length for all text across the site, added this limitation to team member images so that they align to with the text.

all paragraph <p> and header will headers will have this limitation automatically other text tags can add .text-max class.
