### ISSUE TITLE
show badge for nominated target

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#513]
the consortia stamp of approval. even if it doesn't link, having that indicator high on the page was nice.

**Comment by annagree** [comment]
@stockards Any other flag we could use to indicate nominated target besides the fact that there's a tab labeled "Nomination Details"?

**Comment by stockards** [comment]
<img width="388" alt="screen shot 2018-12-04 at 5 49 52 pm" src="https://user-images.githubusercontent.com/38479289/49484764-0ea7fc00-f7ed-11e8-8faa-5849ee49bf09.png">

Ready for review.

**Comment by stockards** [comment]
<img width="593" alt="screen shot 2018-12-14 at 9 30 12 am" src="https://user-images.githubusercontent.com/38479289/50018040-e2297800-ff82-11e8-825e-6b1fba1d1f73.png">

**Comment by annagree** [comment]
@stockards love it!
@diegof18 Can you add this tag under gene name for the genes that are nominated targets?
