### ISSUE TITLE
different text widths on nomination details

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#515]
![screenshot from 2018-10-25 13-43-51](https://user-images.githubusercontent.com/84993/47529219-0c509a80-d85c-11e8-937f-3a911a55b714.png)

**Comment by annagree** [comment]
Text width of bottom part should match that of header.
https://www.figma.com/file/RAV7geFcRz1qvNjk4XFxRKk6/Agora?node-id=2344%3A527
<img width="651" alt="screen shot 2018-10-25 at 2 15 53 pm" src="https://user-images.githubusercontent.com/40642407/47530812-82ef9700-d860-11e8-927f-244d31384f53.png">
