### ISSUE TITLE
use full and proper university names

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#516]
MSSM -> The Icahn School of Medicine at Mount Sinai
Duke -> Duke University

**Comment by gatof81** [comment]
Where you want to use full names?
I don't see full name on the team json.

**Comment by annagree** [comment]
The full name is now available in the updated Json! There are two places I'd like to use full team names. I'll detail them in separate comments. On the Contributing Teams page, I would like to concatenate info from these fields: "program" ":" "team_full". NOte that for one team (Sage Bionetworks) the program field is null so it should just pull from team_full, with no additional colon.

https://www.figma.com/file/RAV7geFcRz1qvNjk4XFxRKk6/Agora?node-id=2886%3A971

**Comment by annagree** [comment]
The second place to update is on the Nomination Details tab. Each team name should now come from the team_full field as well.
<img width="1147" alt="Screen Shot 2019-04-03 at 4 26 39 PM" src="https://user-images.githubusercontent.com/40642407/55519612-705a6480-562d-11e9-819e-a3776e46383a.png">
