### ISSUE TITLE
Forest plot not showing full length of bars

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/Agora#522]
<img width="1095" alt="screen shot 2018-10-25 at 1 47 33 pm" src="https://user-images.githubusercontent.com/2660103/47529595-1757fa80-d85d-11e8-96b0-a107fb7d1ba1.png">

**Comment by annagree** [comment]
For example, for the bottom bar (TCX), the line extends beyond the axis on the right.

**Comment by annagree** [comment]
related to #495

**Comment by Zaknarfen** [comment]
Can you tell me what gene is it so I can reproduce? @annagree @karawoo

**Comment by Zaknarfen** [comment]
Should be fixed, I found the issue.
