### ISSUE TITLE
Mobile: No way to dismiss menu in Chrome on iOS

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#523]
This menu is always present and sometimes obscures other content

![img_7918](https://user-images.githubusercontent.com/4452678/47529544-fe4f4980-d85c-11e8-8c83-b110927a79c5.PNG)

![img_7920](https://user-images.githubusercontent.com/4452678/47529627-2e96e800-d85d-11e8-90ea-10e9eff361cc.PNG)

**Comment by annagree** [comment]
related to #463
