### ISSUE TITLE
webpage using significant memory 

### ISSUE THREAD

**Issue by kelshmo** [Sage-Bionetworks/Agora#524]
![screen shot 2018-10-25 at 1 51 56 pm](https://user-images.githubusercontent.com/40647130/47529649-3c4c6d80-d85d-11e8-8917-f98289fccc78.png)

**Comment by Zaknarfen** [comment]
I don't have a mac, maybe @gatof81 can help you. I found [this](https://discussions.apple.com/thread/8353302).
