### ISSUE TITLE
Feature request - Link to PI website and contact info on team pages

### ISSUE THREAD

**Issue by amapeters** [Sage-Bionetworks/Agora#529]
Add the link to the contact PI for each contributing team

**Comment by annagree** [comment]
@stockards is looking into how best to add links on team page.

**Comment by stockards** [comment]
@Zaknarfen @annagree I made a comment in the Figma file for this. Use an underline to denote a link on the team page. Links will be the same color as the text currently is, without the blue coloring.

**Comment by Zaknarfen** [comment]
We can close this, done in b27c0e4.
