### ISSUE TITLE
Mobile: Menu bar extends off screen in Chrome on iOS

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#531]
Most content is responsive, but not the nomination details/summary of evidence/druggability menu

![img_7923](https://user-images.githubusercontent.com/4452678/47529878-ec21db00-d85d-11e8-9c01-be953c70bec9.PNG)
![img_7924](https://user-images.githubusercontent.com/4452678/47529880-ec21db00-d85d-11e8-8529-9cee67637389.PNG)

**Comment by gatof81** [comment]
did the menu bar scrollable but is not really noticeable maybe @stockards can provide a better design for mobile?
