### ISSUE TITLE
Nominated target list does not show unless zoomed out

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#532]
The little gray bar below the header row is all that I can see of the list unless I zoom out (and it's only gray when mouse over it, otherwise it's white and blends in with the footer)

<img width="1552" alt="screen shot 2018-10-25 at 1 59 16 pm" src="https://user-images.githubusercontent.com/4452678/47530090-79652f80-d85e-11e8-88c5-8e1aad68d441.png">

**Comment by Zaknarfen** [comment]
Should be fixed @karawoo, if not re-open.

**Comment by karawoo** [comment]
@Zaknarfen is the fix deployed already? Looks the same to me, not sure if I need to give it more time though.
