### ISSUE TITLE
Nominated Targets Page: List only shows 1-3 lines at a time

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#535]
Scroll seems to be sticking to the top of the paragraph description. Update so the page scrolls until you get to the table's filter bar/dark blue bar, then allow scroll. 
<img width="1242" alt="screen shot 2018-10-26 at 10 13 36 am" src="https://user-images.githubusercontent.com/38479289/47583123-517fd580-d90b-11e8-8411-a633536b5159.png">

**Comment by annagree** [comment]
related to #526
