### ISSUE TITLE
unexpected behavior in Similar genes table

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#550]
The Similar Genes table is not showing druggability information as expected.
For example, for this gene: https://agora-prod.ampadscicomp.org/genes/(genes-router:gene-similar/ENSG00000171509//gene-overview:rna)

<img width="1617" alt="screen shot 2018-10-31 at 3 12 51 pm" src="https://user-images.githubusercontent.com/40642407/47821921-a2366a80-dd1f-11e8-927c-bfb08654db19.png">

Also true for VGF: https://agora-prod.ampadscicomp.org/genes/(genes-router:gene-similar/ENSG00000128564//gene-overview:rna)

**Comment by gatof81** [comment]
Drugability information doesn't seem to be there.
