### ISSUE TITLE
Dynamic version and data version on website

### ISSUE THREAD

**Issue by zaro0508** [Sage-Bionetworks/Agora#560]
The version and data version on the Agora website seems to be statically defined in the package.json file.  It would be better if this info was more dynamic.  Setting version info to `1.0.0` is not enough information for us to track down the actual commit that was deployed.   I think it should be `<version>-<git sha>`, something like `1.0.0-a5e76c3` would be much more informative.

Also the data version should be dynamically retrieved from the database.  We can do that now that each environment has it's own DB.

**Comment by annagree** [comment]
Agree- let's move to a dynamic site version.

**Comment by annagree** [comment]
@zaro0508 ^^ any thoughts on Renan's comment above?

**Comment by zaro0508** [comment]
For the data version i'm wondering if it would be move that metadata to Sage-Bionetworks/agora-data-manager repo because the agora-data-manager is the actual source that imports data to the DB.  If we move it there Sage-Bionetworks/Agora can read it from agora-data-manager to get the data version.  


Suggestion for adding git sha to the agora version:

I would recommend updating the eb-deploy stage[1] to get the short git shaw and append it to the version.  something like this..

```
GIT_SHORT_SHA = git rev-parse --short HEAD
AGORA_VERSION = 1.0.0-$GITSHORT_SHA
then replace  `version` in package.json[2] with the $AGORA_VERSION
```
Then replace the `git archive ...` with `zip ...`[3] in .travis.yaml file.

[1] https://github.com/Sage-Bionetworks/Agora/blob/develop/.travis.yml#L38
[2] https://github.com/Sage-Bionetworks/Agora/blob/develop/package.json#L3
[3] https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-sourcebundle.html#using-features.deployment.source.commandline

**Comment by Zaknarfen** [comment]
Do you mind doing this part @zaro0508? Seems like you got the idea all sorted out.
