### ISSUE TITLE
All forest plot points are labeled 0.0

### ISSUE THREAD

**Issue by karawoo** [Sage-Bionetworks/Agora#572]
This is gene INPP5D, though it's the case for every gene I've looked at today. All points in the forest plot are labeled 0.0 0.[something obscured by the point]

<img width="1158" alt="screen shot 2018-11-08 at 8 27 45 am" src="https://user-images.githubusercontent.com/4452678/48212353-44fa7480-e330-11e8-87c3-e330ec5b3c86.png">

**Comment by annagree** [comment]
I see this intermittently too. Not clear what triggers it, but can be fixed by hard reset.

**Comment by Zaknarfen** [comment]
I can see this error too for this gene too. I am investigating what it might be.

**Comment by Zaknarfen** [comment]
It should be fixed I found the error.
