### ISSUE TITLE
Evidence Tab: expression plots are not in sync

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#574]
See screenshot: the mean values (dots) on both plots should be equivalent, however the values in the bottom plot seem to be associated with the wrong brain tissue.
For example, VGF. https://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000128564)
In the Differential Expression plot for VGF, DLPFC has a value of -1.27, but this is mixed up in the forest plot and the -1.27 is associated with TCX instead.

**Comment by annagree** [comment]
<img width="1233" alt="screen shot 2018-11-07 at 1 57 28 pm" src="https://user-images.githubusercontent.com/40642407/48229886-31660280-e35e-11e8-920e-00ce8b73418f.png">

**Comment by Zaknarfen** [comment]
Should be fixed in develop.
