### ISSUE TITLE
Similar genes pages have unexpected content below the table

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#582]
The RNA Expression widgets can be seen below the Similar Genes table; this page should just have the table.
https://agora.ampadportal.org/genes/(genes-router:gene-similar/ENSG00000128564//gene-overview:rna)

<img width="776" alt="screen shot 2018-11-12 at 8 36 11 am" src="https://user-images.githubusercontent.com/40642407/48361307-16dda300-e656-11e8-9367-5d61ff71531e.png">

**Comment by gatof81** [comment]
@annagree where did you get that link from?

**Comment by annagree** [comment]
@diegof18  I navigated to the link by clicking on the "Similar Genes" portion of the network widget.

<img width="771" alt="screen shot 2018-11-13 at 6 11 43 pm" src="https://user-images.githubusercontent.com/40642407/48455319-990dba80-e76f-11e8-8c18-75b6439a5f2c.png">
