### ISSUE TITLE
RNA Expression info modal placement is intermittently centered not left aligned

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#586]
I can't always replicate this, but I see this modal being oddly aligned somewhat frequently:
<img width="1084" alt="screen shot 2018-11-12 at 9 15 47 am" src="https://user-images.githubusercontent.com/40642407/48363831-b6e9fb00-e65b-11e8-9073-0fc192ed1d0a.png">

**Comment by Zaknarfen** [comment]
I could not replicate this. I need to know the step to make this happen, if the text is black it is not applying the rules there which is odd. I tried combining navigation and could not see the error. Maybe it is OS related?
