### ISSUE TITLE
links from Nominated Target Page are working

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#591]
As discussed on slack, none of the gene links are working from this page:
https://agora.ampadportal.org/genes/(genes-router:genes-list)

In addition, the link to the nomination form is also not working.

**Comment by annagree** [comment]
We had a user reach out to use because they tried to use the nomination page, but were unsuccessful.

**Comment by annagree** [comment]
@Zaknarfen This link is also not working: https://agora.ampadportal.org/nominated-form

**Comment by Zaknarfen** [comment]
This was fixed. Just waiting to merge to the main site.
