### ISSUE TITLE
Tracking test coverage (on master branch)

### ISSUE THREAD

**Issue by jay-hodgson** [Sage-Bionetworks/Agora#60]
✔ 12 tests completed
TOTAL: 12 SUCCESS

Coverage summary
Statements   : 49.45% ( 181/366 )
Branches     : 0% ( 0/84 )
Functions    : 29.13% ( 30/103 )
Lines        : 46.34% ( 152/328 )

**Comment by kdaily** [comment]
Think we can close this as we now have coveralls.io added.
