### ISSUE TITLE
searching for gene symbol or Ensembl Gene ID

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#608]
We want to add functionality so people can search by either gene symbol or Ensembl Gene ID (note there are other Ensembl ids too, so we will need to specify "Gene".
We need to think about how to either shorten this message or scroll, or otherwise help people understand what fields they can search by.

**Comment by stockards** [comment]
Are you thinking of this as hint text within the search bar on the home page, or something more along the lines of a toggle for the ability to search for gene symbol or Ensembl Gene ID?

**Comment by annagree** [comment]
@stockards I would say both of those sound like possible options. Do you have an opinion on what makes more sense?

**Comment by annagree** [comment]
@stockards They are pretty different, one is typically an abbreviation of the full gene name and the other is a code, for example:
Full name: inositol polyphosphate-5-phosphatase D
Gene Symbol: INPP5D
Ensembl Gene ID: ENSG00000168918

**Comment by annagree** [comment]
Here are a couple sites that allow search of multiple gene names/ids in case it's helpful as an example
https://uswest.ensembl.org/index.html
https://www.genenames.org/

**Comment by stockards** [comment]
This is super helpful thank you @annagree ! I'll be taking a look at this. :)

**Comment by annagree** [comment]
@stockards The main issue right now is that we can't allow them to search in the full gene name, so they have to either know the correct gene symbol or the Ensembl Gene ID.
It could be: Search Gene Symbol or Ensembl ID?

**Comment by annagree** [comment]
See Figma- please update the search field on home page to change font size and capitalize text:
https://www.figma.com/file/RAV7geFcRz1qvNjk4XFxRKk6/Agora?node-id=2489%3A162
