### ISSUE TITLE
plots not loading correctly

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#609]
Still having issues with plots not loading correctly. 
See two screenshots for VGF.

<img width="1418" alt="screen shot 2018-12-02 at 7 15 23 pm" src="https://user-images.githubusercontent.com/40642407/49351110-bd6e0000-f666-11e8-95cc-a8b56de128de.png">
<img width="1301" alt="screen shot 2018-12-02 at 7 15 29 pm" src="https://user-images.githubusercontent.com/40642407/49351112-c1018700-f666-11e8-998e-eea9afcd98a6.png">

**Comment by annagree** [comment]
@Zaknarfen I've now tried two different computers, have cleared cache, and have tried Firefox, Safari and Chrome, and I am seeing this loading issue consistently across all the browsers.

**Comment by annagree** [comment]
@Zaknarfen  Sometimes it can be remedied by a reload. But not always.

**Comment by Zaknarfen** [comment]
From what I could tell there are two errors. The first one is, no errors show up in the console, but the display is just like the one you showed. The second one, all the texts, and rectangles in the forest plot have errors, but they point to the resize callback and we are not resizing anything when we first load the app, so it makes no sense.

Sometimes it doesn't resize incorrectly and the charts show up fine. I will try some changes to see if we can fix this.

**Comment by Zaknarfen** [comment]
I think this is fixed.
