### ISSUE TITLE
Footer should not be sticky

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#613]
There should be a sticky header but not a sticky footer. This seems to only be an issue on the Home page.

**Comment by Zaknarfen** [comment]
If the footer is not sticky it is going to show above the loading screen, because the loading component is an overlay. Should we change this? what is happening in the home page that is wrong?

**Comment by stockards** [comment]
You have to scroll in order to see the search bar. You shouldn't see the footer until you have scrolled past the scroll bar on the home page.
<img width="1217" alt="screen shot 2018-12-07 at 3 32 13 pm" src="https://user-images.githubusercontent.com/38479289/49677768-5751f600-fa35-11e8-9e0e-fd28fb957005.png">

**Comment by annagree** [comment]
Home page footer behavior is not correct in Chrome.
