### ISSUE TITLE
Incorrect styling for selected table item

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#616]
In Nominated Targets, when an item is selected it should not have a drop shadow. Just the blue selection.

Also please replace the blue with the transparency of 3F5EAB.

**Comment by Zaknarfen** [comment]
I fixed this. Should we add something for every table column `th` element on focus? Now when we use tab there it goes through the three columns and there is no way of telling where is it. Also, I made it so that each row gets a focus on tab clicking.
