### ISSUE TITLE
Gene Descriptions when there is 'no description'

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#617]
Please leave empty instead of saying "no description". Bar can resize appropriately for the lack of content.

**Comment by stockards** [comment]
<img width="1218" alt="screen shot 2018-12-04 at 6 32 55 pm" src="https://user-images.githubusercontent.com/38479289/49486381-0a7edd00-f7f3-11e8-930c-b29d29666c0f.png">

**Comment by annagree** [comment]
@gatof81 If null (or No Description) just show blank
