### ISSUE TITLE
Ability to click content boxes on Gene Page

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#619]
User should not be able to click the boxes on the gene page in order to see a dropshadow on all of them.
<img width="1190" alt="screen shot 2018-12-04 at 6 35 18 pm" src="https://user-images.githubusercontent.com/38479289/49486465-6a758380-f7f3-11e8-9da1-97806fc5650c.png">

**Comment by Zaknarfen** [comment]
FIxed this.
