### ISSUE TITLE
Teams page

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#625]
Teams should have a separator which is a 2 px line in #E0E0E0 and not boxes with dropshadows.

You can follow what is on the other pages in Figma. I can also mock up if needed.

<img width="1204" alt="screen shot 2018-12-04 at 6 50 40 pm" src="https://user-images.githubusercontent.com/38479289/49487031-93971380-f7f5-11e8-9287-d8f23540e34e.png">

**Comment by gatof81** [comment]
![image](https://user-images.githubusercontent.com/1027130/49652990-6d9a8a80-fa12-11e8-9c5c-572d7f03c834.png)
 this is how it looks on figma, boxes with drop shadows, I changed it to a 2px line separator but can you update figma?
