### ISSUE TITLE
Sage Team is missing images 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#626]
<img width="1180" alt="screen shot 2018-12-04 at 6 52 03 pm" src="https://user-images.githubusercontent.com/38479289/49487067-b9bcb380-f7f5-11e8-8b00-91dc8a8853c5.png">

**Comment by gatof81** [comment]
mongo import needs to be run again on the server in order to work.

**Comment by Zaknarfen** [comment]
I believe it is solved now reopen if not.

**Comment by zaro0508** [comment]
Just to let people know.  There is automation in place that will allow anyone to update the Agora DB.  https://github.com/Sage-Bionetworks/agora-data-manager
