### ISSUE TITLE
Help video

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#627]
Can we also use Vimeo for this and choose another screen?
<img width="1197" alt="screen shot 2018-12-04 at 6 53 46 pm" src="https://user-images.githubusercontent.com/38479289/49487130-01dbd600-f7f6-11e8-9252-c1b6f37ebb57.png">

**Comment by stockards** [comment]
Same with the video below for Synapse.

**Comment by annagree** [comment]
@stockards Good catch- and I think we probably need to remake the video so it matches V2 formatting!

**Comment by annagree** [comment]
MOved to Jira
