### ISSUE TITLE
Terms and privacy page incorrect styling

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#628]
• Fonts are not styled correctly. 
• Footer does not stick to the bottom.

**Comment by gatof81** [comment]
the footer looks sticky to me, could have been fixed on a previous commit or might be different platform or browser specific? can you please check and clarify.

fonts are set to Lato medium 22px didn't find a figma reference to check correct font.

**Comment by stockards** [comment]
I'm on Chrome and this is how it looks.
<img width="1212" alt="screen shot 2018-12-07 at 8 51 28 am" src="https://user-images.githubusercontent.com/38479289/49661213-556c4080-f9fd-11e8-8913-ec41870d96e9.png">

**Comment by stockards** [comment]
The text should follow the body copy text which is used throughout the site.

**Comment by Zaknarfen** [comment]
I think I got it fixed let me know if we need to reopen.
