### ISSUE TITLE
Loading screen design issues 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#629]
This happened when I clicked on a gene from the Nominated Targets page. Not sure if it is happening elsewhere but the footer should be sticking to the bottom, not floating in the middle. Loading icon should be in the middle of the page. 

<img width="1173" alt="screen shot 2018-12-05 at 11 38 43 am" src="https://user-images.githubusercontent.com/38479289/49539540-b4597a80-f882-11e8-8cde-8d6515485d5e.png">

**Comment by annagree** [comment]
Let's monitor this and see if it keeps coming up. Might need to create a new separate loading page.
