### ISSUE TITLE
tabs do not always update to present information on new selected gene

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#631]
I recorded what happened when clicking through to different genes on the site:

1. Visit Home
2. Click Nominated Targets
3. Select C1QTNF4 gene
4. View tabs

Quit Chrome and restarted browser.

1. Visit Home
2. Visit Nominated Targets page
3. Select ATP6V1A gene
     a. Taken to Nomination Details tab
     b. Click to View Summary 
     c. Click to View Evidence 
4. Visit Nominated Targets page
5. Select ALK gene
    a. Taken to Evidence tab (**should be taken to Nomination Details tab**), the graph doesn't completely render, but the first red dot is **incorrectly showing last gene viewed ATP6V1A**
    b. Click on Nomination Details tab (also **incorrectly showing information for last gene viewed ATP6V1A**)
6. Visit Nominated Targets page
7. Select CSF1R gene
    a. Taken to Nomination Details page (correctly showing info for CSF1R)
    b. Click on Evidence tab, incomplete render of plots, **incorrectly showing data for C1QTNF4** (which was a gene I viewed before closing and restarting the browser, 3 genes back in the list).

**Comment by Zaknarfen** [comment]
Fixed it.
