### ISSUE TITLE
genes with no expression data- blank plots should be showing

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#636]
Genes with no expression data should still show plots- just with the message "No expression data is currently available". This was implemented at one time, but it might have been before we switched to tab layout. Now, the components are just hidden entirely, although network widget is visible?

See example: https://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000147437)

<img width="356" alt="screen shot 2018-12-13 at 4 12 26 pm" src="https://user-images.githubusercontent.com/40642407/49975265-0426ea00-fef2-11e8-8b89-bf3bd0efda47.png">

**Comment by Zaknarfen** [comment]
I think the network uses another `api` request, so even with no expression data, the links between genes might be there. If there are links the network renders I believe. I'll look into the hidden thing.

**Comment by Zaknarfen** [comment]
Now that we fixed the charts I am getting `404` for that gene. I'll add the new `Not found` page and we can check this at the meeting.

**Comment by Zaknarfen** [comment]
I think this is solved, I added the `404` error page and there should not be an invalid request to the `gene` collection, only genes without `gene-info`.
