### ISSUE TITLE
Hint text in search bar on Nominated Targets page should match Home Page 

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#637]
<img width="1222" alt="screen shot 2018-12-14 at 9 57 35 am" src="https://user-images.githubusercontent.com/38479289/50019215-bdcf9a80-ff86-11e8-8288-4b120bb3536e.png">

**Comment by annagree** [comment]
@Zaknarfen @diegof18 Not sure if we are linking nominated targets to Ensembl IDs yet? If this is easy to implement, please do, then change search text as needed.
