### ISSUE TITLE
hitting enter in the search bar should not go to new line

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#642]
Currently hitting enter in the search bar on home page will go to a new line and then a scroll bar pops up.

Nominated targets search bar is working as expected.

<img width="1261" alt="screen shot 2018-12-14 at 1 44 49 pm" src="https://user-images.githubusercontent.com/40642407/50029131-bfa95600-ffa6-11e8-877f-f5dccdb05cff.png">

**Comment by gatof81** [comment]
just removed the new line, enter won't trigger the search
