### ISSUE TITLE
selected genes fail to load

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#650]
Gene pages for many genes are failing to load:
https://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000147437)
https://agora.ampadportal.org/genes/(genes-router:gene-details/ENSG00000196591)

I haven't done comprehensive testing yet, but so far nominated targets seem to load, but all non-nominated targets are not loading.

**Comment by annagree** [comment]
@gatof81 @Zaknarfen These two example genes are in the input gene.info file. I confirmed that I can see them in the raw data. Even if there is no expression data, there is basic gene description and summary data for these genes. The gene pages should be rendered even without expression data to show. 

Note that the first one (ENSG00000147437) is one I've been testing with throughout the process (GNRH1). I know that there used to be a gene page for this gene, even as recently as 2 weeks ago.

This might be related to #636?

**Comment by Zaknarfen** [comment]
If you take a look at [this](https://agora.ampadportal.org/api/gene/?id=ENSG00000147437) and scroll all the way down it says `item: null`. That is the query result for a gene. It comes from [here](https://github.com/Sage-Bionetworks/Agora/blob/develop/src/server/routes/api.ts#L328).

We perform two searches there, one in the `genes` collection using the `rnaseq_differential_expression.json` file and a second one in the `geneinfo` collection using the `gene_info.json` file. The second query finds the info but the first does not find the gene itself.

I can take a look after I am back or Diego can look at it.

**Comment by gatof81** [comment]
You can check it in development, I’ll push everything into staging tomorrow.
