### ISSUE TITLE
look into programmatically linking to Open Targets website

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#651]
Within the Summary tab we want to link to external information on the Open Targets site about a gene's association with AD. 
We can either use the API or potentially programmatically update the URL to point to Open Targets.
For example, here is the link for the CC1QTNF4 gene showing its association with AD: 
https://www.targetvalidation.org/evidence/ENSG00000172247/EFO_0000249

The EFO_0000249 part of the URL specifies AD. 

Here is the RESTful API info:
https://api.opentargets.io/v3/platform/docs/swagger-ui

**Comment by annagree** [comment]
One thing to look into is what happens if a gene on open targets does not show an association with AD. Where does that take people? @annagree to look into this.

**Comment by annagree** [comment]
@Zaknarfen Once you update the URL to include the AD link, we'll also need to adjust where it is linked to from the table. 
See new image from Figma.
The Open Targets link should be under a new category "Evidence for AD Association". The link should read "Visit Open Targets"
I'd also like to update the text for Reactome pathways and Gene Ontology to read "Visit Ensembl"

<img width="782" alt="screen shot 2019-02-11 at 3 51 00 pm" src="https://user-images.githubusercontent.com/40642407/52602136-5616be00-2e16-11e9-92f6-73204f945f64.png">

**Comment by Zaknarfen** [comment]
Last commit [bc17128](https://github.com/Sage-Bionetworks/Agora/commit/bc171288a2510415c3e73e9d4b4e99e2d62e9531) addresses this. We can close this, reopen if we still have issues.
