### ISSUE TITLE
what's new page or section?

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#653]

**Comment by stockards** [comment]
What we have done that is new and why you should care. ie: New nominations, new sections, etc. Maybe it's "News"? In the footer?

**Comment by annagree** [comment]
See draft of content here: https://docs.google.com/document/d/1yOl0mKELW-LMBGM7OeySgr8fbXGBMZIyprtvO6Ii9Ok/edit

**Comment by stockards** [comment]
New screen for 'News'. @Zaknarfen note the new footer update. 

![what s new](https://user-images.githubusercontent.com/38479289/53368066-9db04600-38fc-11e9-8924-8bd820bd365b.png)

**Comment by Zaknarfen** [comment]
Updated by fd8b81d.

**Comment by annagree** [comment]
@annagree needs to generate content for this.
