### ISSUE TITLE
modal styling bugs

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#655]
A few of the modals have styling that needs to be updated.
Here are screen shots, let me know if you need more details: 
<img width="1142" alt="screen shot 2019-02-11 at 3 54 06 pm" src="https://user-images.githubusercontent.com/40642407/52601974-9fb2d900-2e15-11e9-8fb6-35142fee8a35.png">
<img width="1049" alt="screen shot 2019-02-11 at 3 52 57 pm" src="https://user-images.githubusercontent.com/40642407/52601982-a4778d00-2e15-11e9-9f28-a030805357c2.png">
<img width="1114" alt="screen shot 2019-02-11 at 3 52 18 pm" src="https://user-images.githubusercontent.com/40642407/52601991-ad685e80-2e15-11e9-8f67-0f70337a2531.png">

**Comment by Zaknarfen** [comment]
Last commit bc17128 addresses this. We can close this, reopen if we still have issues.
