### ISSUE TITLE
clarification on new design for druggability information

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#656]
We are updating the display of druggability buckets per @stockards designs. 
But, for now we should use the existing bucket information that is in the field associated with each nominated target, rather than the text from figma. We will be able to add the new text once we next update the data in Agora. 
So, in the interim it should be:

<img width="1266" alt="screen shot 2019-02-12 at 1 07 04 pm" src="https://user-images.githubusercontent.com/40642407/52668155-9b46f880-2ec7-11e9-88f4-ae92af82114b.png">

Let me know if you have any questions about this.

**Comment by Zaknarfen** [comment]
Fixed by b921e41.
