### ISSUE TITLE
Update Loading Icon

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#662]
https://codepen.io/valentinfrancois/pen/VpebJj

@Zaknarfen Would it be possible to try the loader which is 2nd down on the left, and make it a bit slower as well? Can use color #5171C0. I'd love to potentially make it a bit more personalized but would love to see from you how complex that is first. Thanks!

**Comment by Zaknarfen** [comment]
![image](https://user-images.githubusercontent.com/4223973/53444448-f232ee80-39ec-11e9-8e0a-79279dc6287b.png)

We can modify the colors easily, I would need to see how the fill changes with different colors.

**Comment by stockards** [comment]
Wonderful! Let's plan to chat with this on our stand up call this week. :)

**Comment by Zaknarfen** [comment]
Sure, by the way, @stockards and @annagree, (develop)[https://agora-develop.ampadportal.org/genes/(genes-router:gene-details/ENSG00000128564)] has a preview of the new loading and the download widget now downloads the `.png` right away. It doesn't take forever anymore.
