### ISSUE TITLE
Wrong Color/Number/Title for Druggability

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#665]
I'm not sure which of these items is incorrect, but the number/color/title isn't matching up in this instance of Druggability for VGF. I suspect it is happening on others as well. 

Details of correct number/color/title can be found in Figma. 

<img width="698" alt="screen shot 2019-03-05 at 2 27 39 pm" src="https://user-images.githubusercontent.com/38479289/53842006-23627000-3f53-11e9-8637-a0e9e17a3e4f.png">

**Comment by Zaknarfen** [comment]
I was using the first header, `h2`, with the incorrect `color` and `font-weight`. I've updated it, let me know if we can close this.
