### ISSUE TITLE
Make loading icons consistent

### ISSUE THREAD

**Issue by stockards** [Sage-Bionetworks/Agora#668]
I saw the new loading icon, the old loading icon and the loading icon with "loading...". Please make these all match the new loading icon.

**Comment by Zaknarfen** [comment]
@annagree @stockards I think there is not old loading anymore, what should I do with the initial pre-app `Loading...` message? Should it be the same white background and loading than the rest? I might have to duplicate the code for that since this happens before the app is loaded.

**Comment by stockards** [comment]
Not sure if I'm following but yes, ideally it should be the same so the white with the loading icon.
