### ISSUE TITLE
teams page: apostrophe rendering

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#679]
There's an apostrophe that isn't correct in one of the team entries. Is this something you can fix in the front end or do we need to wait for another data update?

<img width="832" alt="Screen Shot 2019-04-05 at 12 08 19 PM" src="https://user-images.githubusercontent.com/40642407/55650883-ce0cbf00-579b-11e9-84c3-fcda8a7b39ea.png">

**Comment by Zaknarfen** [comment]
This error is coming from the dataset itself. I will put a temporary solution to it, but it should be fixed at the source also.
