### ISSUE TITLE
include gene "alias" field in search

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#690]
There is a field called "alias" in the gene_info.json file. Let's try including this in the search box on the home page and see how it impacts search performance.

**Comment by Zaknarfen** [comment]
Closed by d5fa8d4.

**Comment by annagree** [comment]
As discussed, searching for synonyms can lead to unexpected results. If I search "SHIP-1" I will only see INPP5D as what I can select. Is it possible to add the aliases to the string that is returned in the search bar? Then, if I searched for SHIP-1  I would see:
INPP5D (Also known as SHIP, SHIP-1, SHIP1, SIP-145, hp51CN, p150Ship)

**Comment by annagree** [comment]
@Zaknarfen I've been testing the alias search feature and have found a few bugs. 

First, I have found few cases when the (Also known as...) message does not show up. 

Gene name= C1QTNF4
CTRP4 did NOT show the message
ZACRP4 did NOT show the message

Gene name = BIN1
AMPH2 did NOT show the message
AMPH DID show the message
CMN2 DID show the message
SH3P9 did NOT show the message (though SH3P did)

In other cases, the wrong gene shows up. I wonder if it's sometimes showing results on a partial string match?
For example, the gene ODF3 showed up when I searched SHIP, but its alias is actually SHIPPO1.

**Comment by Zaknarfen** [comment]
About both problems. For the first one, after inspection, I think staging is showing the aliases so no missing aliases.

![image](https://user-images.githubusercontent.com/4223973/58194202-46233b80-7c9b-11e9-815a-b3c9906d14d6.png)

![image](https://user-images.githubusercontent.com/4223973/58194514-132d7780-7c9c-11e9-8079-9081954de870.png)

I'll fix that scrolling to the right also, shouldn't be there.

About the second problem, you are right, should be an exact match not partial. I set it in a way that it was searching just for parts like the gene name.

**Comment by annagree** [comment]
This is working as expected on staging now- closing this.
