### ISSUE TITLE
search bar- make icon smaller and increase font size

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#699]
As discussed, the font should be bigger (18pt) and the magnifying glass icon should be smaller in the search bars. 
<img width="1432" alt="Screen Shot 2019-06-14 at 7 54 01 AM" src="https://user-images.githubusercontent.com/40642407/59716906-b609e080-91cb-11e9-9526-3c187ef0e860.png">

**Comment by Zaknarfen** [comment]
Closed by a0a9056.
