### ISSUE TITLE
update text in SM Druggability bucket 14

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#704]
There should be a return between "Non-protein target" and "New modality indicated". Currently they are on the same line (see screenshot).
<img width="1507" alt="Screen Shot 2019-06-26 at 9 35 31 AM" src="https://user-images.githubusercontent.com/40642407/60198214-eff36c00-97f5-11e9-8f1b-117017bd82a9.png">

**Comment by Zaknarfen** [comment]
Anna, can you check if this is solved? I don't see that anymore on staging, just tested it for CLU.

**Comment by annagree** [comment]
Yes this looks resolved on staging. Thanks!
