### ISSUE TITLE
summary tab is showing wrong info for non-nominated gene

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#705]
See this gene as an example: https://agora-staging.ampadportal.org/genes/(genes-router:gene-details/ENSG00000137642)

The summary tab shows "AMP-AD Evidence", but doesn't show the summary table. See screenshot. 
<img width="1246" alt="Screen Shot 2019-06-26 at 10 27 38 AM" src="https://user-images.githubusercontent.com/40642407/60201473-31d3e080-97fd-11e9-93e7-216c79e97588.png">

**Comment by Zaknarfen** [comment]
I see the summary just fine. Can you check it again? maybe it was still the old version. If you still have this error let me know your steps.

![image](https://user-images.githubusercontent.com/4223973/60203358-d74d7b00-9822-11e9-8ce0-e95930776cb2.png)

**Comment by annagree** [comment]
@Zaknarfen I was able to reproduce this error on the new staging site. It is fine when I first go to the page, but then after navigating to "Evidence" and then back to "Summary" it shows the wrong info.
