### ISSUE TITLE
aliases in gene search are still not working as expected

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#706]
This is on staging site. See the attached screenshot. Many genes show up with the searched alias APOD: 
<img width="1375" alt="Screen Shot 2019-06-26 at 10 23 46 AM" src="https://user-images.githubusercontent.com/40642407/60201595-7b243000-97fd-11e9-91e6-f09e01dc1f88.png">

**Comment by Zaknarfen** [comment]
Anna, I think that is happening after a few searches maybe I don't see that on the first search. If you just type APOD it works fine if you erase a letter then type it in again you'll see those results you got but they should vanish and show the correct one afterward. I'll make a patch for it.
