### ISSUE TITLE
clicking nominate a target button does not lead to form

### ISSUE THREAD

**Issue by annagree** [Sage-Bionetworks/Agora#707]
On staging, clicking the "Nominate a target" button does not lead to the form as it should. 
https://agora.ampadportal.org/genes/(genes-router:nominated-form)

**Comment by Zaknarfen** [comment]
I see the form just fine Anna, maybe it was the old version still. Can you check that again?

**Comment by annagree** [comment]
@Zaknarfen I am looking at the new version now, but the form is still not showing up for me.

**Comment by Zaknarfen** [comment]
https://agora-staging.ampadportal.org/genes/(genes-router:nominated-form)

![image](https://user-images.githubusercontent.com/4223973/60207249-cbb28200-982b-11e9-97af-fcb4c63c3c34.png)

This is weird, try maybe clearing your cache.

**Comment by annagree** [comment]
Yeah I see it just fine on a different browser. It's just me!
